; generated by compiler

extern printf
format db '%u', 0
global main
main:
enter 0, 0
mov eax, 1 ; eax = 1
mov edx, 1 ; edx = 1
imul eax, edx ; eax += edx
mov ecx, 1 ; ecx = 1
mov ebx, 1 ; ebx = 1
imul ecx, ebx ; ecx += ebx
add eax, ecx ; eax += ecx
mov ecx, 1 ; ecx = 1
mov esi, 1 ; esi = 1
imul ecx, esi ; ecx += esi
mov edi, 1 ; edi = 1
mov ebp, 1 ; ebp = 1
imul edi, ebp ; edi += ebp
mov esp, 1 ; esp = 1
add edi, esp ; edi += esp
mov esp, 1 ; esp = 1
imul edi, esp ; edi += esp
add ecx, edi ; ecx += edi
add eax, ecx ; eax += ecx
mov ecx, 1 ; ecx = 1
mov edi, 1 ; edi = 1
imul ecx, edi ; ecx += edi
add eax, ecx ; eax += ecx
mov ecx, 1 ; ecx = 1
add eax, ecx ; eax += ecx
mov dword [null + 0], eax ; dword [null + 0] = eax
push dword [ebp - 4]
push format
call printf
add esp, 12

mov eax, 0
leave
ret